baseURL = 'https://ihavethatonvinyl.com'
languageCode = 'en-us'
theme = 'ihavethatonvinyl'
title = 'I Have That on Vinyl'

enableRobotsTXT = true

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss']
  term = ['html', 'rss']

[services]
  [services.googleAnalytics]
    id = 'G-BBP1Q2MPB5'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.136.0"

# Taxonomy terms
[taxonomies]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
