baseURL = 'https://ihavethatonvinyl.com'
languageCode = 'en-us'
title = 'I Have That on Vinyl'
theme = 'ihavethatonvinyl'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.136.0"

# Taxonomy terms
[taxonomies]
  q-and-a = "q-and-a"
  conversation = "conversations"
  essay = "essays"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
