baseURL = 'https://ihavethatonvinyl.com'
languageCode = 'en-us'
title = 'I Have That on Vinyl'
theme = 'ihavethatonvinyl'

enableRobotsTXT = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.136.0"

# Taxonomy terms
[taxonomies]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
