name = 'I Have That On Vinyl'
license = 'MIT'
licenselink = 'https://github.com/ihavethatonvinyl/theme/LICENSE'
description = 'Custom theme for I Have That On Vinyl'
min_version = "0.136.0"

# The home page of the theme, where the source can be found
homepage = 'https://github.com/ihavethatonvinyl/theme'

# If the theme has a single author
[author]
  name = 'Josh Ghiloni'
  homepage = 'https://joshghiloni.me'
