on:
  workflow_dispatch:
    inputs:
      target-environment:
        type: choice
        description: Are you posting to staging or the live site?
        options:
          - staging
          - live
      include-drafts:
        type: boolean
        description: "Include Drafts?"
      
jobs:
  build-site:
    runs-on: [ihavethatonvinyl-runners]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build inputs
        id: build-inputs
        env:
          TARGET_ENV: ${{ github.event.inputs.target-environment }}
        run: |
          base_url="https://vinyl-staging.michelecatalano.me"
          if [[ "${TARGET_ENV}" == "live" ]]; then
            base_url="https://ihavethatonvinyl.com"
          fi

          echo "BASE_URL=${base_url}" >> ${GITHUB_OUTPUT}
          echo "IMAGE_NAME=registry.lab.verysmart.house/images/ihavethatonvinyl:latest-${TARGET_ENV?:-staging}" >> ${GITHUB_OUTPUT}
      - name: Build Hugo Site
        uses: .github/actions/build-hugo-image/action.yml
        with:
          base-url: ${{ steps.build-inputs.outputs.BASE_URL }}
          include-drafts: "${{ github.event.inputs.include-drafts }}"
          image-name: ${{ steps.build-inputs.outputs.IMAGE_NAME }}
          registry-hostname: registry.lab.verysmart.house
          registry-username: "robot$images+gha"
