name: Publish Blog (staging and live)

on:
  schedule:
    - cron: "55 * * * *"
  workflow_dispatch: {}
      
jobs:
  build-site:
    runs-on: [ihavethatonvinyl-runners]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build inputs
        id: build-inputs
        env:
          TARGET_ENV: staging
        run: |
          base_url="https://staging.ihavethatonvinyl.com"
          if [[ "${TARGET_ENV}" == "live" ]]; then
            base_url="https://ihavethatonvinyl.com"
          fi

          echo "BASE_URL=${base_url}" >> ${GITHUB_OUTPUT}
          echo "IMAGE_NAME=registry.lab.verysmart.house/images/ihavethatonvinyl" >> ${GITHUB_OUTPUT}
          echo "IMAGE_TAG=${TARGET_ENV}-${GITHUB_SHA:0:7}" >> ${GITHUB_OUTPUT}
      - name: Build Hugo Site
        uses: ./actions/build-hugo-image/
        with:
          base-url: ${{ steps.build-inputs.outputs.BASE_URL }}
          image-name: ${{ steps.build-inputs.outputs.IMAGE_NAME }}
          image-tag: ${{ steps.build-inputs.outputs.IMAGE_TAG }}
          registry-hostname: registry.lab.verysmart.house
          registry-username: "robot$images+gha"
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: install Helm
        uses: Azure/setup-helm@v4.2.0
      - name: update chart if necessary
        env:
          IMAGE_NAME: ${{ steps.build-inputs.outputs.IMAGE_NAME }}
          IMAGE_TAG: ${{ steps.build-inputs.outputs.IMAGE_TAG }}
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        shell: bash
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBE_CONFIG}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

          suffix=""
          if [[ $IMAGE_TAG =~ staging* ]]; then
            suffix="-staging"
          fi

          helm upgrade --install \
            ihavethatonvinyl${suffix} chart/ihtov --namespace ihtov${suffix} \
            -f chart/ihtov/values${suffix}.yaml --set image.tag=${IMAGE_TAG}
            
